### ISSUE TITLE
Extrat data from historical reports

### ISSUE THREAD

**Issue by olivermueller** [soetang/xbrlr#3]
Hi Benjamin,

nice work! Interesting to see how this evolved from a class project to a career ;-)

You know that we would like to extract information from historical reports (that is, not the current period, but let's say 2014 or 2015) and we don't know how to navigate the contexts. Do you have a function similar to get_this_period_dk() that returns the relevant Danish tags for a given year (e.g., get_year_dk(year))?

Best,
Oliver

**Comment by soetang** [comment]
Hey Oliver,

I put this project together this week, so still work on the naming of functions, this might be the reason for the confusion. What you really want to do is to download the xbrl document for the specific years:

E.g. for the company "Eldorado A/S": 
2017 report:  https://datacvr.virk.dk/data/offentliggorelse?dl_ref=ZG9rdW1lbnRsYWdlcjovLzAzLzc5LzI2L2RmLzI3L2M5OWMtNDYyMi1iMjEyLTdlOWY4YjYzNDFiOQ 

2016 report:  https://datacvr.virk.dk/data/offentliggorelse?dl_ref=ZG9rdW1lbnRsYWdlcjovLzAzL2E2L2IxLzg3L2U4L2EzN2EtNDllNi1hNDY4LTU4OTAwZDIxYmVjOQ

If you parse each report one at a time and use get_this_period_dk(), will return the numbers from the respective years. It's true that the 2018 report might contain some of the data from the 2017 report, however it will not include the text from the 2017 report. So the best option really is to download the reports from 2013, 2014, 2015 and so on and then parse each of them one at a time.

Does this make sense?

**Comment by soetang** [comment]
So get_this_period_dk just looks up which year this specific document is from and then filters the context based on that, the code for get_this_period_dk should not be too complex if you want to have a look. Just a few dplyr operations.

**Comment by soetang** [comment]
Update -  I just added two new things that might be interesting for you:

1.  get_this_period_de() roughly equivalent to the Danish function (excepts for prefixes, see below)
2.  get_this_period_dk now prefixes variable names according to the namespace. Eg.  the arr prefix indicates that the data is part of the auditors' review and mrv is referring to management review.
